### ISSUE TITLE
Apache segfaults on the default php version

### ISSUE THREAD

**Issue by sriddell** [Unicon/simplesamlphp-dockerized#1]
Great project; saved me a lot of time getting a simple IDP running.

I noticed however that I would get frequent empty responses, which I traced back to the httpd process seg faulting with an AH00052 error.

From some research, I believe it's related to this php bug: https://bugs.launchpad.net/ubuntu/+source/php5/+bug/1407990.

I tried a Dockerfile installing php 5.5 instead, and it appeared to correct the problem.

Specifically, I changed the first RUN block to be

RUN yum -y install epel-release \
    && rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    && rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm \
    && yum -y update \
    && yum -y install php55w mod_ssl php55w-mcrypt php55w-pear php55w-xml php55w-pdo wget \
    && yum -y clean all

In order to install php 5.5 instead, which contains the fix.

Not certain if that's the right thing to do, but it appears to have fixed the issue for me well enough to use the docker image in dev environments (which is all I need it for right now).

Wanted to report it in case anyone else has run into it.

**Comment by jtgasper3** [comment]
@sriddell,

Thanks for reporting this. I believe we use this image internally, I'm surprised we aren't experiencing any issues (or at least know that anyone has shared). 

I'll double check to confirm that my team doesn't mind a bump in PHP versions.

**Comment by jtgasper3** [comment]
The Dockerfile has been updated to install PHP 5.5. It does use the WebTatic repo as you do as I couldn't get the SCL to work properly in a reasonable amount of time. I've also added tags for a few missing versions. I also subscribed to the SSP announcements mailing list so I get notified of new versions.
